# Generated by Django 3.2.6 on 2021-08-22 17:06

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='House',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('address', models.CharField(max_length=255)),
                ('code', models.CharField(max_length=30)),
                ('iptu_code', models.CharField(max_length=30)),
                ('real_state_registry_code', models.CharField(max_length=30)),
                ('area', models.IntegerField()),
                ('tv_room', models.IntegerField()),
                ('living_room', models.IntegerField()),
                ('bedroom', models.IntegerField()),
                ('office', models.IntegerField()),
                ('cellar', models.IntegerField()),
                ('bathroom', models.IntegerField()),
                ('laundry_room', models.IntegerField()),
                ('kitchen', models.IntegerField()),
                ('more_details', models.CharField(max_length=255)),
                ('parking_spaces', models.IntegerField()),
                ('elevator', models.BooleanField()),
                ('piped_gas', models.BooleanField()),
                ('gas_included_in_the_condominium_price', models.BooleanField()),
                ('water_included_in_the_condominium_price', models.BooleanField()),
                ('rent_amount', models.IntegerField()),
                ('condominium_price', models.IntegerField()),
                ('situation', models.CharField(max_length=10)),
                ('property_value', models.IntegerField()),
                ('responsible', models.CharField(max_length=50)),
                ('updated_at', models.DateField()),
                ('created_at', models.DateField(default=django.utils.timezone.now)),
            ],
        ),
    ]
